### PR TITLE
Move Easy Installer above Manual Install

### PR DESCRIPTION
**Pull request by vjFaLk**
It's better for non-advanced users

### CODE REVIEW

**Comment by rmehta** [comment]
@vjFaLk this is by design. users must understand what the easy install does!

**Comment by vjFaLk** [comment]
@rmehta Hmm, a user's first instinct would be to start with the top, maybe then add a link to the Easy Install at the top?

**Comment by rmehta** [comment]
I think this reads alright the way it is... closing this.

**Comment by vjFaLk** [comment]
💔

**Comment by rmehta** [comment]
Sometimes its better to know what you are getting into :)

**Pull request closed without merging**
