### PR TITLE
Adding .git directory in ignore list for site backup bench command

### PR DESCRIPTION
**Pull request by jigartarpara**
exclude .git directory from all site backup bench command
it will help if we want to maintain the repo for sites folder for the project

### CODE REVIEW

**Comment by achillesrasquinha** [comment]
How did the .git directory even land there?

**Comment by jigartarpara** [comment]
Because I initialized there 
Purpose: To track changes and backup of config files of all sites available in multitenant environment

**Comment by achillesrasquinha** [comment]
that's limited to your use case, don't you think?

**Comment by codingCoffee** [comment]
Closing PR as It seems limited to your use case. Also it seems you've messed with the file permissions, and given all of them 755, hence it is showing 165 files changes in the diff! :thinking: Highly recommended to go back to 644 using chmod

**Comment by jigartarpara** [comment]
Sure, will do
Thank you

**Pull request closed without merging**
