### PR TITLE
feat: Implemented Backups for Easy Install setups

### PR DESCRIPTION
**Pull request by athul**
- Enable backups for Easy Install setups
- Adds the backup script for the project to crontab(uses `subprocess.run`)

Thanks to @revant <3

What type of a PR is this?

- [ ] Changes to Existing Features
- [x] New Feature Submissions
- [ ] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

---

> Please provide enough information so that others can review your pull request:

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [ ] Have you lint your code locally prior to submission?
- [ ] Have you successfully run tests with your changes locally?
- [ ] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

> Screenshots/GIFs

Screenshot 2023-01-19 at 3 47 47 PM

The screenshot was made by commenting out the prod setup and only just the backup was enabled

### CODE REVIEW

**Comment by revant** [comment]
Shouldn't it be `--skip-backup` instead of `--backup`?
So that it just creates a basic db dump like native bench does.

**Comment by athul** [comment]
> Shouldn't it be --skip-backup instead of --backup?

Currently I don't think the backups are automatically added to a system-level cron with docker based setups and even if they are it won't be doing anything because of the new docker layer.

**Comment by athul** [comment]
Updated the Script to take backups by default. Will update readme and resolve conflicts post review

**Review by revant — APPROVED** [review]
LGTM

**Comment by athul** [comment]
Resolved conflicts and updated readme

**Pull request closed without merging**
