### PR TITLE
fix: Upgrade Ansible to 2.8.15 (or later patch version)

### PR DESCRIPTION
**Pull request by ceefour**
What type of a PR is this?

- [x] Bug Fix

---

> Please provide enough information so that others can review your pull request:

Upgrade Ansible to 2.8.15 (or later patch version)

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?

---

Related to #1052.

> Screenshots/GIFs

### CODE REVIEW

**Comment by ceefour** [comment]
BTW I installed Erpnext with Ansible 2.9.x without issues. Should I make the PR use 2.9.x instead?

**Comment by gavindsouza** [comment]
> BTW I installed Erpnext with Ansible 2.9.x without issues. Should I make the PR use 2.9.x instead?

No, not until there's a good reason to do so.

**Review by gavindsouza — CHANGES_REQUESTED** [review]
Can you rebase and make a semantic commit message? Else, I will squash and do the same with your PR.

**Comment by ceefour** [comment]
@gavindsouza Rebased with semantic commit

**Review by gavindsouza — APPROVED** [review]

**Pull request merged**
