### PR TITLE
chore: bump jinja

### LINKED ISSUE #1269: bump jinja
smallish breaking change in markupsafe is breaking all CI / installs:

ref: https://github.com/pallets/jinja/issues/1585#issuecomment-1043892628

ref ci run: https://github.com/frappe/frappe/runs/5243197059?check_suite_focus=true#step:13:91

### PR DESCRIPTION
**Pull request by ankush**
https://jinja.palletsprojects.com/en/3.0.x/changes/

bench only seems to use jinja for rendering config files, tested locally. 

closes #1269

### CODE REVIEW

**Review by ChillarAnand — APPROVED** [review]

**Comment by ankush** [comment]
tests failing because of frappe deps
https://github.com/frappe/frappe/blob/749f32bb4e39d646dd34c4b8d60cc1f49d246635/requirements.txt#L27

https://github.com/frappe/frappe/blob/8cc808a90fd97baa2320c4864f2a127eef574518/requirements.txt#L29

**Comment by pipech** [comment]
Are there any reason that you didn't bump jinja on `master` branch?

https://github.com/frappe/bench/blob/8b0d522b639575e0fd651ddcd5cd5ab6b91d43c4/requirements.txt#L4

It currently breaking the installation.

@ankush 

```
Traceback (most recent call last):

  File "/usr/local/bin/bench", line 11, in <module>

    load_entry_point('bench', 'console_scripts', 'bench')()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point

    return ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load

    return self.resolve()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/home/frappe/bench-repo/bench/__init__.py", line 1, in <module>

    from jinja2 import Environment, PackageLoader

  File "/usr/local/lib/python3.7/dist-packages/jinja2/__init__.py", line 33, in <module>

    from jinja2.environment import Environment, Template

  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 15, in <module>

    from jinja2 import nodes

  File "/usr/local/lib/python3.7/dist-packages/jinja2/nodes.py", line 19, in <module>

    from jinja2.utils import Markup

  File "/usr/local/lib/python3.7/dist-packages/jinja2/utils.py", line 642, in <module>

    from markupsafe import Markup, escape, soft_unicode

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/dist-packages/markupsafe/__init__.py)
```

**Comment by ankush** [comment]
> Are there any reason that you didn't bump jinja on master branch?


`develop` is the default development branch and `v5.x` is the stable branch. Don't use the master branch.

**Comment by pipech** [comment]
> > Are there any reason that you didn't bump jinja on master branch?
> 
> `develop` is the default development branch and `v5.x` is the stable branch. Don't use the master branch.

Hmm, may I ask what is the point of `master` branch?

**Comment by ankush** [comment]
I don't know. Sometimes back it was switched. It's probably kept to avoid breaking other's workflow (if someone was fetching it for manual install)

**Pull request merged**
