### PR TITLE
fix-mysql-error

### PR DESCRIPTION
**Pull request by elba7r**
this pull request fix the mysql installation error

### CODE REVIEW

**Comment by elba7r** [comment]
hello everyone i have found that there is an installation error appear and after a lot of investigations i found the reason which had been fixed in this pull request so please apply it because its a global error facing everyone start to install frappe since 8 days ago . thx

**Comment by codingCoffee** [comment]
Hey @elba7r ,
this PR can be closed. I sent in a PR #543 targeting the root cause of the problem

**Comment by yanncopp** [comment]
The Frappe Bench easy installation doesn't work !!!! Any solution ?????

**Comment by saurabh6790** [comment]
already fixed via PR #543

**Pull request closed without merging**
