### PR TITLE
feat: Changed function download_translations_p in bench/utils.py to use multithreading.

### PR DESCRIPTION
**Pull request by Aradhya-Tripathi**
the function uses multiple processes for an I/O bound task using threading would improve the performance significantly as spinning up processes takes longer than using threads.

### CODE REVIEW

**Comment by ankush** [comment]
Can you add rough benchmarks?

**Comment by Aradhya-Tripathi** [comment]
[
process
](url)
Time taken to run the function using multiprocessing
threading
Time taken to run the function using threads

**Comment by Aradhya-Tripathi** [comment]
As you can see there is a significant boost when using threads as compared to multiple processes.

**Comment by gavindsouza** [comment]
> [ process ](url)
> Time taken to run the function using multiprocessing
> threading
> Time taken to run the function using threads

Mention the code snippet and/or command that gave you this output too @Aradhya-Tripathi

**Comment by gavindsouza** [comment]
On another note, translations are [included in frappe](https://github.com/frappe/frappe/tree/develop/frappe/translations) directly for a while now. This looks like legacy code. 

New translation commands exist under `frappe.commands.translate` module. Using this command would make changes in the apps folder. Maybe we should just get rid of these now. 🤔

**Comment by Aradhya-Tripathi** [comment]
> On another note, translations are [included in frappe](https://github.com/frappe/frappe/tree/develop/frappe/translations) directly for a while now. This looks like legacy code.
> 
> New translation commands exist under `frappe.commands.translate` module. Using this command would make changes in the apps folder. Maybe we should just get rid of these now.

image
there one uses processes and one uses threads
```
def download_translations_t():
	## Refractored code

	from concurrent.futures import ThreadPoolExecutor

	start = time.time()

	with ThreadPoolExecutor() as pool:
		langs = get_langs()
		apps = ('frappe', 'erpnext')
		args = list(itertools.product(apps, langs))

		pool.map(update_translations_p, args)
	end = time.time()

	print(f"TIME TAKEN BY REFRACTORED FUNCTION {end-start}")
```

**Comment by gavindsouza** [comment]
Closing this as the function should be deprecated now instead of optimising it.

**Pull request closed without merging**
