### PR TITLE
feat: skip redis config during supervisor setup

### PR DESCRIPTION
**Pull request by revant**
skips redis configuration during `bench setup supervisor --skip-redis`
In case redis is not installed locally and used as a remote service it causes redis processes to fail with command not found.

### CODE REVIEW

**Comment by gavindsouza** [comment]
@revant LGTM. Can you update the [Documentation Page](https://frappeframework.com/docs/user/en/bench/bench-commands) too?

**Comment by revant** [comment]
https://frappeframework.com/docs/user/en/bench/bench-commands#setup-commands

Setup commands don't document optional param here.
Should I add an option just for supervisor command?

**Comment by gavindsouza** [comment]
Yeah, in a format similar to Frappe commands' docs. 

eg: [Site Deletion](https://frappeframework.com/docs/user/en/bench/frappe-commands#site-deletion) section with a seperate page for [usage reference](https://frappeframework.com/docs/user/en/bench/reference/drop-site)

**Comment by revant** [comment]
added it somewhere else. I think it is relevant where supervisor is setup.

okay?

**Comment by gavindsouza** [comment]
Yeah. Updating the reference guide is cool but IMO this should be on the documentation first.

**Comment by revant** [comment]
If someone adds the setup section, I'll edit it.

**Review by gavindsouza — APPROVED** [review]

**Pull request merged**
