### PR TITLE
fix(config): Fix fail2ban filter

### PR DESCRIPTION
**Pull request by deajan**
What type of a PR is this?

- [X] Bug Fix

---
This fixes the fail2ban playbook where nginx-proxy filter isn't installed
Also allows fail2ban to check all nginx access logs.
On the nginx side, it adds a log directive so different sites get different access logs for easier debugging.

- [X] Have you followed the guidelines in our Contributing document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [X] Have you lint your code locally prior to submission?
- [X] Have you successfully run tests with your changes locally?
- [X] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [N/A] Docs have been added / updated
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Did you modify the existing test cases? If yes, why?

---

### CODE REVIEW

**Review by gavindsouza — CHANGES_REQUESTED** [review]
Hey @deajan, thanks for your contribution. Went through your proposed changes and LGTM.

Can you make your commit messages semantic? We use a semantic release tool which may not be able to generate the next release (& notes) properly if they're not fixed before merging.

I believe your commits are of type: fix, fix. feat respectively. LMK if you need any help in making the changes.

**Comment by deajan** [comment]
Hello @gavindsouza, do you mean you want all 3 commit messages in this PR to have the type in it ?
Ie: `Add all nginx log files to fail2ban filter, regardless of frappe site` would become `feat: Add all nginx log files to fail2ban filter, regardless of frappe site` ?
Thanks.

**Comment by gavindsouza** [comment]
> Hello @gavindsouza, do you mean you want all 3 commit messages in this PR to have the type in it ? Ie: `Add all nginx log files to fail2ban filter, regardless of frappe site` would become `feat: Add all nginx log files to fail2ban filter, regardless of frappe site` ? Thanks.

Yes! Each commit is a separate change and will be classified and mapped as such in the release notes (For eg: https://github.com/frappe/bench/releases/tag/v5.8.0).

**Review by gavindsouza — APPROVED** [review]

**Comment by Tom-Finke** [comment]
Nginx throws a an error

> nginx: [emerg] unknown log format "main" in

I traced it back to this PR.
Why was the log format main added to the access log and where should it be defined?

**Pull request merged**
