### PR TITLE
Force install pdfkit for new environments

### LINKED ISSUE #719: New Environment requires PDFKit by Force

### PR DESCRIPTION
**Pull request by achillesrasquinha**
Fixes #719

### CODE REVIEW

**Comment by codingCoffee** [comment]
Already exists in exists in https://github.com/frappe/frappe/blob/develop/setup.py#L54

**Comment by achillesrasquinha** [comment]
For some reason, it breaks during env migration. Check the list of installations prior to setup env

**Comment by codingCoffee** [comment]
So I faced this error today while migrating. This should technically fix the issue, but it doesn't ! :/

**Comment by sagarvora** [comment]
Not needed anymore, fixed in #744

**Pull request closed without merging**
