### PR TITLE
add symlink to setup nginx

### PR DESCRIPTION
**Pull request by RobertSchouten**

### CODE REVIEW

**Comment by vjFaLk** [comment]
What's the idea behind this? Bench already creates a nginx.conf in the config folder that has a symlink to a file in conf.d

**Comment by RobertSchouten** [comment]
The goal behind this is starting from a develop environment running Bench setup nginx seems confusing that it doesn't actually fully setup nginx

**Comment by vjFaLk** [comment]
The development environment doesn't use nginx **at all**. What are you trying to achieve exactly?

**Comment by shreyasp** [comment]
@RobertSchouten But in case of, development we serve sites using Werkzeug server which is started by command `bench serve --port <port>` in Procfile. We haven't used Nginx for serving our development sites.

**Comment by RobertSchouten** [comment]
the case is using a develop vm in bridged mode so it has it's own ip and me being lazy and not wanting to type the port in to access the site

**Comment by vjFaLk** [comment]
@RobertSchouten 😅 You can already do that if you have DNS Multitenant enabled, and no default site (no currentsite.txt in sites folder) just add entries to the /etc/hosts file for the domain name that point to the IP of your VM. I've been using that kind of setup for my own workflow. Let me know if you have any trouble with that on Discuss. 

I'm gonna close this PR 😄

**Comment by RobertSchouten** [comment]
np just seemed like could of improved but havent gotten into dns multiteant but was in my todo so ill do that

**Pull request closed without merging**
