### PR TITLE
fix: run backups every 6 hours, rather than every minute per 6 hours

### PR DESCRIPTION
**Pull request by Alchez**
What type of a PR is this?

- [ ] Changes to Existing Features
- [ ] New Feature Submissions
- [x] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you lint your code locally prior to submission?
- [ ] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

**Problem:**

For newer benches, the crontab would be set to generate backups every _minute_ per 6 hours, as opposed to running it every 6 hours.

**Solution:**

Fix the crontab generation accordingly

**Reference:**

From the [`python-crontab`](https://pypi.org/project/python-crontab/) package documentation:

> Proceeding Unit Confusion

> It is sometimes logical to think that job.hour.every(2) will set all proceeding units to ‘0’ and thus result in “0 */2 * * *”. Instead you are controlling only the hours units and the minute column is unaffected. The real result would be “* */2 * * *” and maybe unexpected to those unfamiliar with crontabs.

> There is a special ‘every’ method on a job to clear the job’s existing schedule and replace it with a simple single unit:

> ```
> job.every(4).hours()  == '0 */4 * * *'
> job.every().dom()     == '0 0 * * *'
> job.every().month()   == '0 0 0 * *'
> job.every(2).dows()   == '0 0 * * */2'
> ```

> This is a convenience method only, it does normal things with the existing api.

### CODE REVIEW

**Comment by Alchez** [comment]
@gavindsouza, this might need a patch for existing systems, can you help with that please?

**Comment by gavindsouza** [comment]
Sample cron record created by the buggy `job.hour.every(6)`:
```
* */6 * * * cd /absolute/path/to/bench && /Users/gavin/.pyenv/versions/3.7.7/bin/bench --verbose --site all backup  >> /absolute/path/to/bench/logs/backup.log 2>&1 #   bench auto backups set for every 6 hours
```

Parsing the crontab file, line by line, and replacing the cron expression if it matches the backup command is what seems like an acceptable solution to me. Will you write the patch for this?

**Comment by Alchez** [comment]
@gavindsouza, I've added a patch for the cron fix, but I'm not sure how to run it. A `bench migrate` didn't do that.

**Comment by gavindsouza** [comment]
@Alchez `bench migrate` is a frappe command. `bench update` runs the bench patches. You can run it with the `--patch` flag to run patches and migrate all sites on the current bench

**Comment by Alchez** [comment]
@gavindsouza, I ran `bench update --patch` and even `bench update` but the patch doesn't seem to run. Can you test on your side and see if you can get it to trigger?

**Comment by gavindsouza** [comment]
@Alchez works for me. Check `patches.txt` in your bench; It records which patches are run and need not be run again. Remove the record if it exists and try again.

**Comment by Alchez** [comment]
@gavindsouza, my `patches.txt` in the root bench directory only has one patch in it - `bench.patches.v3.deprecate_old_config`

Unless you mean a different file, I can't seem to make the patch run. If you think it's good to go though, we can move this ahead.

**Pull request merged**
