### PR TITLE
fix: set referrer-policy header in nginx config

### PR DESCRIPTION
**Pull request by Thunderbottom**
sets the "Referrer-Policy" header to "strict-origin-when-cross-origin", with "same-origin" as a fallback

setting the referrer policy prevents sharing site context to external links, preventing cross-site hijacking or tab nagging.

ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

### CODE REVIEW

**Comment by surajshetty3416** [comment]
@Thunderbottom will this update already created nginx configs?

**Comment by Thunderbottom** [comment]
no, this does not. requires a `bench setup nginx` to run.

**Comment by surajshetty3416** [comment]
@Thunderbottom Can we add an info/warning message for users to update their nginx config?

**Comment by Thunderbottom** [comment]
yeah, will have to see how exactly to do it.

**Review by gavindsouza — APPROVED** [review]

**Pull request merged**
