### PR TITLE
fix: fixed org, branch for apps mounted on disk

### LINKED ISSUE #1288: `org`, `repo` and `tag` set to unrelated values
https://github.com/frappe/bench/blob/1337f9c1a5f59b1de3bff4f67831ce90c7d66690/bench/app.py#L106-L109

Suppose `self.bench.name` is the current directory (`"."`), self.name is `"frappe"`, self.branch is `"version-13"`.:

```
self.org, self.repo, self.tag =  os.path.split( 
    os.path.join(".", "apps", "frappe") 
)[-2:] + ("version-13",) 
```
 
Which is the same as 

```
self.org, self.repo, self.tag =  ('./apps', 'frappe', 'version-13')
```

Apart from the fact that `repo == self.name` this seems to produce garbage.

### PR DESCRIPTION
**Pull request by Aradhya-Tripathi**
* Before
image

* After
image

Fixes: #1288

### CODE REVIEW

**Comment by gavindsouza** [comment]
Screenshot 2022-04-12 at 10 13 54 AM

Added a print and `name` seems to be `git@github.com:gavindsouza/frappe.git`

**Comment by gavindsouza** [comment]
Also, this happened on `bench setup requirements` when an app not from the Frappe org was on bench:

Screenshot 2022-04-12 at 11 05 57 AM

**Comment by Aradhya-Tripathi** [comment]
> d345fbb

fixed by [d345fbb](https://github.com/frappe/bench/pull/1293/commits/d345fbb75cf18b3df51f7eb5f53cebd8f41aee8a)

**Comment by Aradhya-Tripathi** [comment]
> Screenshot 2022-04-12 at 10 13 54 AM
> 
> Added a print and `name` seems to be `git@github.com:gavindsouza/frappe.git`

fixed by [d345fbb](https://github.com/frappe/bench/pull/1293/commits/d345fbb75cf18b3df51f7eb5f53cebd8f41aee8a)

**Comment by Aradhya-Tripathi** [comment]
> Also, this happened on `bench setup requirements` when an app not from the Frappe org was on bench:
> 
> Screenshot 2022-04-12 at 11 05 57 AM


> Also, this happened on `bench setup requirements` when an app not from the Frappe org was on bench:
> 
> Screenshot 2022-04-12 at 11 05 57 AM



> Also, this happened on `bench setup requirements` when an app not from the Frappe org was on bench:
> 
> Screenshot 2022-04-12 at 11 05 57 AM

fixed by 
120ddf8

**Comment by gavindsouza** [comment]
@Aradhya-Tripathi Got this via `bench setup requirements`:

Screenshot 2022-04-18 at 3 58 47 PM

Handle apps with no remotes

**Pull request merged**
