### PR TITLE
feat: Inform user of change in configuration files

### LINKED ISSUE #1035: Watcher for config updates
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
There are updates in the bench config files and are usually security related. But they get overlooked as the configs don't get regenerated automatically. 

**Describe the solution you'd like**
Something that checks if there are config changes that haven't been applied to your bench. It hints you to regenerate the configs again. This can be triggered on certain bench command executions similar to https://github.com/frappe/bench/pull/960. Move these to a watcher functions list that execute on triggers perhaps.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

### PR DESCRIPTION
**Pull request by anirudhdggl**
What type of a PR is this?

- [ ] Changes to Existing Features
- [x] New Feature Submissions
- [ ] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

---

## Explanation

Whenever there is a change in any config file in a bench, within the config directory, the user has to ensure that he restarts the bench. If at any time user forgets to restart the relevant bench, a warning will be presented to him on the CLI stating that he needs to restart the bench in order for the configuration changes to take effect

---

## Screenshots

image
image
image

closes: #1035

### CODE REVIEW

**Comment by anirudhdggl** [comment]
@gavindsouza I'll be fixing the CI tests - but can you help me with the sematic PR?

I've mentioned the PR title as specified in the contribution guidelines and also included a commit for the same. Is something missing from the title / commit?

**Comment by anirudhdggl** [comment]
Added a fix as well - for existing bench, where the config log filedo not exist. Initially this would've caused an error but now we would prompt the user to run `bench restart` command.

Bench restart would then go and create the config log file and from next time onwards whenever a change is made to any config file, there would be a message prompting users to restart bench

image

**Comment by gavindsouza** [comment]
hey @anirudhdggl, thanks for your contribution. This is certainly going to be useful to remind users to reload their bench's processes. Although, one bit does come up that any command that updates config files also restarts the processes by default. This is a good-to-have but we could better move this elsewhere and not trigger it every time someone uses the CLI.

---

However, this doesn't resolve the mentioned issue. Issue #1035 is about telling users that they should reset their config files because we've made changes in them - this could be adding performance, security, or bug fixes. ie, whenever changes are made in the template files (ref:[nginx config template]( https://github.com/frappe/bench/blob/develop/bench/config/templates/nginx.conf)), and an end-user updates their bench package, there should be a mechanism in place that finds and resolves outdated configs.

**Comment by anirudhdggl** [comment]
Okay - so basically #1035 is that whenever any file is changed in this [directory](https://github.com/frappe/bench/tree/develop/bench/config/templates) in GitHub, this exact location, we should ask the users to make the relevant changes to their local configs? Am I understanding it correctly?

And is this just for the `.conf` files or all the files (even within the subdirectory) in this directory?

**Comment by gavindsouza** [comment]
> Okay - so basically #1035 is that whenever any file is changed in this [directory](https://github.com/frappe/bench/tree/develop/bench/config/templates) in GitHub, this exact location, we should ask the users to make the relevant changes to their local configs? Am I understanding it correctly?

Yes! Nicely put, thanks.



> And is this just for the `.conf` files or all the files (even within the subdirectory) in this directory?

This, I didn't fully follow.

---

@anirudhdggl Hope this thread didn't die out. I've been caught up with other things, apologies 🥲

**Pull request closed without merging**
