### PR TITLE
fix(easy-install): read values from env if exists

### PR DESCRIPTION
**Pull request by revant**
#1610

### CODE REVIEW

**Comment by NagariaHussain** [comment]
Will test today 👍

**Comment by revant** [comment]
No change in docs. Command remains same, explained here: https://github.com/frappe/bench?tab=readme-ov-file#arguments

**Comment by NagariaHussain** [comment]
Cool, will test and merge today 👍

**Comment by NagariaHussain** [comment]
I tried running the `upgrade` command with an updated backup cron string. It did update the env, but not the actual container it seems:

CleanShot 2024-12-31 at 12 34 12@2x

CleanShot 2024-12-31 at 12 34 02@2x

**Pull request merged**
