### PR TITLE
feat(nginx): Allow logging settings as site/combined/none

### LINKED ISSUE #1351: Unable to start (reload) nginx
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:

 Unable to start (reload) nginx.

```
$ sudo systemctl start nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```

**To Reproduce** :page_with_curl:

1. Use frappe-bench 5.13.x
2. `bench setup nginx --yes` (as frappe user)
3. `sudo systemctl start nginx` (as sudor)

**OS (please complete the following information):** :cyclone:
- [x] Linux: Ubuntu 20.04

**Version Information**

- Bench Branch: v5.13.x

**Possible Solution** :bookmark_tabs:

The nginx template seems broken since this [commit](https://github.com/frappe/bench/pull/1308/commits/c61e993a789b4d9c13b6129f026a19b93a70f523). @deajan @gavindsouza 

```
sudo nginx -t
nginx: [emerg] unknown "site_name_ihrkdqy_access" variable
nginx: configuration file /etc/nginx/nginx.conf test failed
```

### PR DESCRIPTION
**Pull request by gavindsouza**
Defaults to NGINX access + error logs combined for all sites. Site level granularity in log generation is optional, and so is not logging at all.

NGINX Guides: https://docs.nginx.com/nginx/admin-guide/monitoring/logging/

> Note: If you haven't installed NGINX via `bench install nginx`, then run `bench setup nginx --log_format ''` to set no log_format

Closes https://github.com/frappe/bench/issues/1351 caused by https://github.com/frappe/bench/pull/1308

### CODE REVIEW

**Comment by git-avc** [comment]
1. bench setup nginx --logging none -> Don't generate log lines and nginx -t says syntax ok.
2. bench setup nginx --logging combined -> Generate lines without sitename and with "main" modifier . Syntax wrong on nginx -t
3. bench setup nginx --logging site -> Generates lines with $host variable and "main" modifier. Syntax wrong on nginx -t.

I think there are 2 different issues here ... one related to "main" modifier, and other related to "{{site_name}}

**Comment by gavindsouza** [comment]
So, we have the `log_format` defined in the nginx playbook that's triggered by `bench install nginx` 

https://github.com/frappe/bench/blob/391dcf1e12b5646e2f09657a18a69e517c16a001/bench/playbooks/roles/nginx/templates/nginx.conf.j2#L19-L22

For `bench setup nginx` to handle a different log_format now, we can add a way to configure this but it should probably default to log_format alone.

---

@git-avc You haven't installed nginx through bench, have you?

**Comment by git-avc** [comment]
No, installed via apt.
apt -y install nginx

**Comment by gavindsouza** [comment]
Essentially, installing nginx via `bench install nginx` sets up the log_format `main` which `bench setup nginx`'s logging depends on. When one installs NGINX via another package manager, main isn't necessarily defined.

I'll make the log_format setting configurable via the setup command so that you can use any other.

**Comment by git-avc** [comment]
Yeah, i can see ... i think few people install nginx through bench ... First time I know. I will use that from now.
Thanks Gavin!

**Pull request merged**
