### PR TITLE
fix: utf8mb4_general_ci

### PR DESCRIPTION
**Pull request by adamtang79**
fix: prevent error while bench new-site

### CODE REVIEW

**Comment by gavindsouza** [comment]
@adamtang79 Can you update the branch so that the checks pass and we can get this merged?

**Comment by adamtang79** [comment]
> @adamtang79 Can you update the branch so that the checks pass and we can get this merged?

Hi @gavindsouza , I'm sorry I've deleted the fork month ago. I don't have the branch right now. Is there anything I can do?

**Comment by gavindsouza** [comment]
> Hi @gavindsouza , I'm sorry I've deleted the fork month ago. I don't have the branch right now. Is there anything I can do?

@adamtang79 I think you'd have to raise a new PR with the same changes. Since it's a small change, it shouldn't take long to do.

**Comment by adamtang79** [comment]
> > Hi @gavindsouza , I'm sorry I've deleted the fork month ago. I don't have the branch right now. Is there anything I can do?
> 
> @adamtang79 I think you'd have to raise a new PR with the same changes. Since it's a small change, it shouldn't take long to do.

Okay. @gavindsouza  https://github.com/frappe/bench/pull/1093

**Pull request closed without merging**
