### PR TITLE
feat: Added option to provide custom queues

### PR DESCRIPTION
**Pull request by fproldan**
What type of a PR is this?

- [ ] Changes to Existing Features
- [x] New Feature Submissions
- [ ] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

--------------

This PR adds the option to configure a new settings in `common_site_config.json` that allows creating custom workers besides the defaults hardcoded in `supervisor.conf`.

The new setting is named "workers" and should be in this format:
```json
"workers": {
    "<queue_name>": {
        "timeout": <timeout>, 
        "background_workers": <workers>,
    }   
 }
```

Example:
```json
"workers": {
    "myqueue": {
        "timeout": 5000, 
        "background_workers": 4,
    }   
 }
```

The background_workers param is optional, if not set the general `background_workers` will be used.

### CODE REVIEW

**Review by gavindsouza — CHANGES_REQUESTED** [review]
Thanks for your contribution 💯 

I think the config key `workers` would be more accurate instead of `custom_queues`, since they are actually just named workers not queues.

**Comment by fproldan** [comment]
@gavindsouza changes made!

**Comment by gavindsouza** [comment]
LGTM, can you raise a PR that adds docs to `frappe/frappe_docs` too?

**Review by gavindsouza — APPROVED** [review]

**Comment by gavindsouza** [comment]
@fproldan We missed adding this to the Procfile 😅 . Can you raise a PR for the same?

**Comment by fproldan** [comment]
@gavindsouza  done!

**Pull request merged**
